services:
  - type: web
    name: addictiontube-unified2
    runtime: python
    runtimeVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 --timeout 120 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: WEAVIATE_API_KEY
        sync: false
      - key: WEAVIATE_CLUSTER_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000  # Optional, Render overrides with dynamic port
